django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls")),
    path('users/', include("django.contrib.auth.urls")),
    path('', include("real_estate.urls"), name="home")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import SignUpView, profile, logout_view, EditAccountView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
    path("logout/", logout_view, name="logout"),
    path("profile/", profile, name="profile"),
    path('edit_account/', EditAccountView.as_view(), name='edit_account'),
]

real_estate/forms.py
from django import forms
from django.forms import ClearableFileInput
from .models import Listing, PropertyType, ListingType, ListingImage

class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        exclude = ['owner']


class ImageForm(forms.ModelForm):
    image = forms.ImageField(label='Image')
    class Meta:
        model = ListingImage
        fields = ('image', )

class ListingFilterForm(forms.Form):
    num_rooms = forms.IntegerField(required=False)
    city = forms.CharField(max_length=70, required=False)
    region = forms.CharField(max_length=70, required=False)
    property_type = forms.ModelChoiceField(queryset=PropertyType.objects.all(), required=False)
    listing_type = forms.ModelChoiceField(queryset=ListingType.objects.all(), required=False)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Newspaper App{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <header class="p-3 mb-3 border-bottom">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-between">

                    <!-- Left section: "Real Estate" -->
                    <a class="navbar-brand mb-0 h1" href="{% url 'home' %}">Real Estate</a>

                    <!-- Center section: "New Listing" -->
                    <div class="text-center">
                        <ul class="nav">
                            {% if user.is_authenticated %}
                                <li><a href="{% url 'new_listing' %}">New Listing</a></li>
                            {% endif %}
                        </ul>
                    </div>

                    <!-- Right section: "user.username" dropdown -->
                    <div class="text-end">
                        {% if user.is_authenticated %}
                            <div class="dropdown">
                                <a href="#" class="link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user.username }}
                                </a>

                                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                                    <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'my_listings'%}">My Listings</a></li>
                                    <li><a class="dropdown-item" href="{% url 'my_bookings'%}">My Bookings</a></li>
                                    <li><a class="dropdown-item" href="{% url 'password_change'%}">Change password</a></li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
                                </ul>
                            </div>
                        {% else %}
                            <a href="{% url 'login' %}" class="btn btn-outline-primary me-2">Log In</a>
                            <a href="{% url 'signup' %}" class="btn btn-primary">Sign Up</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </header>

        <main>
            {% block content %}
            {% endblock content %}
        </main>
    </div>

    <!-- Bootstrap JavaScript and Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

templates/bookings.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}

  <div class="container" style="margin-top: 50px">
    <div class="row justify-content-center">
      {% for booked_listing in booked_listings %}
        <div class="card mb-3 mx-auto" style="max-width: 800px; position: relative;">
          <div class="row g-0">
            <div class="col-md-4">
              {% if booked_listing.listing.images.first %}
                <img style="margin-top: 10px" src="{{ booked_listing.listing.images.first.image.url }}" class="img-fluid rounded" alt="Listing Image">
              {% else %}
                <!-- Add a default image or a placeholder image -->
                <img src="post_images/default.png" class="img-fluid rounded-start" alt="Default Image">
              {% endif %}
            </div>

            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title">{{ booked_listing }}</h5>
                <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                <p class="card-text"><small class="text-muted">{{ booked_listing.listing.created_at }}</small></p><br>
              </div>
            </div>
          </div>

          <div class="d-flex justify-content-end mb-3">
            <a href="{% url 'listing' id=booked_listing.listing.id %}" class="btn btn-primary me-3">Details</a>
          </div>

          <!--
          <form method="post" action="{% url 'cancel_booking' booked_listing.id %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary position-absolute bottom-0 end-0 m-3">Cancel the booking</button>
          </form>
          -->
        </div>
      {% empty %}
        <p style="text-align: center; margin-top: 30px">You do not have any bookings yet...</p>
      {% endfor %}
    </div>
  </div>
{% endblock content %}

templates/edit_account.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit Account</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save Changes</button>
  </form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="container" style="margin-top: 50px">
    <div class="row">
      <div class="col-md-3 border-end gray" >
        <form method="get" id="filter-form" action="{% url 'home' %}" class="mb-3" >
          <div class="mb-3">
            <label for="id_num_rooms" class="form-label">Number of Rooms:</label><br>
            {{ filter_form.num_rooms }}
          </div>

          <div class="mb-3">
            <label for="id_city" class="form-label">City:</label><br>
            {{ filter_form.city }}
          </div>

          <div class="mb-3">
            <label for="id_region" class="form-label">Region:</label><br>
            {{ filter_form.region }}
          </div>

          <div class="mb-3">
            <label for="id_property_type" class="form-label">Property Type:</label><br>
            {{ filter_form.property_type }}
          </div>

          <div class="mb-3">
            <label for="id_listing_type" class="form-label">Listing Type:</label><br>
            {{ filter_form.listing_type }}
          </div>

          <button type="submit" class="btn btn-primary">Apply Filters:</button>

          <button type="button" class="btn btn-secondary" onclick="resetForm()">Reset Form</button>
        </form>
      </div>

      <div class="col-md-8" style="">
        <div class="row justify-content-center">
            {% if listings %}
              <div class="mb-3">
                <p class="fw-bold">Filter Results:</p>
                <div class="d-flex flex-wrap">
                  {% if filter_form.cleaned_data.num_rooms %}
                    <div class="me-3">
                      <p class="mb-0">Number of Rooms: {{ filter_form.cleaned_data.num_rooms }}</p>
                    </div>
                  {% endif %}
                  {% if filter_form.cleaned_data.city %}
                    <div class="me-3">
                      <p class="mb-0">City: {{ filter_form.cleaned_data.city }}</p>
                    </div>
                  {% endif %}
                  {% if filter_form.cleaned_data.region %}
                    <div class="me-3">
                      <p class="mb-0">Region: {{ filter_form.cleaned_data.region }}</p>
                    </div>
                  {% endif %}
                  {% if filter_form.cleaned_data.property_type %}
                    <div class="me-3">
                      <p class="mb-0">Property Type: {{ filter_form.cleaned_data.property_type }}</p>
                    </div>
                  {% endif %}
                  {% if filter_form.cleaned_data.listing_type %}
                    <div class="me-3">
                      <p class="mb-0">Listing Type: {{ filter_form.cleaned_data.listing_type }}</p>
                    </div>
                  {% endif %}
                </div>
              </div>
            {% endif %}


          {% for listing in listings %}
            <div class="card mb-3 mx-auto" style="max-width: 800px; position: relative;">
              <div class="row g-0">
                <div class="col-md-4" style="margin-top: 10px">
                  {% if listing.images.all %}
                      <img src="{{ listing.images.first.image.url }}" class="img-fluid rounded" alt="Listing Image">
                  {% else %}
                      <p>No images available</p>
                  {% endif %}
                </div>

                <div class="col-md-8">
                  <div class="card-body">
                    <div class="d-flex justify-content-between">
                      <h5 class="card-title">{{ listing }}</h5>
                      <p class="card-text"><small class="text-muted">For {{ listing.listing_type.listing_type }}</small></p>
                    </div>
                    <p class="card-text">Region: {{listing.region}}.   City: {{listing.city}}.   Street: {{listing.address}}</p>
                    <p class="card-text"><small class="text-muted">{{ listing.created_at }}</small></p>
                  </div>
                </div>
              </div>

              <!-- Button Section (Details and Book Now) -->
              <div class="d-flex justify-content-end mb-3">
                <a href="{% url 'listing' id=listing.id %}" class="btn btn-primary me-3">Details</a>
              </div>

            </div>
          {% empty %}
            <p style="text-align: center; margin-top: 30px">No listings available...</p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>


<script>
  function toggleFilterForm() {
      var form = document.getElementById("filter-form");
      form.classList.toggle("d-none");
  }

  function resetForm() {
      var form = document.getElementById("filter-form");
      var elements = form.elements;

      for (var i = 0; i < elements.length; i++) {
          if (elements[i].type !== "submit") {
              elements[i].value = "";
              elements[i].checked = false;
              elements[i].selectedIndex = 0;
          }
      }
  }
</script>
{% endblock content %}

templates/listing.html
{% extends 'base.html' %}

{% block title %}Property Details - Real Estate{% endblock title %}

{% block content %}
<style>
    body {
        font-family: 'Arial', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
    }

    .product-container {
        max-width: 800px;
        margin: 2em auto;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        padding: 2em;
        border-radius: 8px;
    }

    .carousel-inner img {
        width: 100%;
        height: auto;
        border-radius: 8px;
    }

    .product-info {
        font-size: 1.2em;
        margin-top: 20px;
    }

    .product-info p {
        margin-bottom: 10px;
    }

    .info-label {
        font-weight: bold;
    }

    .info-value {
        color: #3498db;
    }
</style>

<div class="product-container">
    {% if listing.images.all %}
        <div id="imageCarousel" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for image in listing.images.all %}
                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                        <img src="{{ image.image.url }}" class="d-block w-100" alt="Listing Image">
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#imageCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#imageCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    {% else %}
        <p>No images available.</p>
    {% endif %}

    <div class="product-info">
        <p><span class="info-label">Listing Type:</span> <span class="info-value">{{ listing.listing_type }}</span></p>
        <p><span class="info-label">Property Type:</span> <span class="info-value">{{ listing.property_type }}</span></p>
        {% if listing.listing_type.listing_type == 'rent' %}
            <p><span class="info-label">Rent cost per month:</span> <span class="info-value">${{ listing.cost }}</span></p>
        {% else %}
            <p><span class="info-label">Cost:</span> <span class="info-value">${{ listing.cost }}</span></p>
        {% endif %}
        <p><span class="info-label">Owner:</span> <span class="info-value">{{ listing.owner }}</span></p>
        <p><span class="info-label">City:</span> <span class="info-value">{{ listing.city }}</span></p>
        <p><span class="info-label">Region:</span> <span class="info-value">{{ listing.region }}</span></p>
        <p><span class="info-label">Address:</span> <span class="info-value">{{ listing.address }}</span></p>
        <p><span class="info-label">Number of Rooms:</span> <span class="info-value">{{ listing.num_rooms }}</span></p>
        <p><span class="info-label">Number of Bedrooms:</span> <span class="info-value">{{ listing.num_bedroom }}</span></p>
        <p><span class="info-label">Number of Bathrooms:</span> <span class="info-value">{{ listing.num_bathrooms }}</span></p>
        <p><span class="info-label">Size:</span> <span class="info-value">{{ listing.size }}m^2</span></p><br>

        <p><span class="info-label">Booking Cost:</span> <span class="info-value">${{ listing.booking_cost }}</span></p>
        <p>If you cancel the booking, only 70% of your money will be refunded!</p>
        <p><span class="info-label">Booked:</span> <span class="info-value">{{ listing.booked }}</span></p>
    </div>

    {% if listing.owner != current_user %}
        {% if listing.is_active %}
            <form method="post" action="{% url 'book_listing' listing.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Book Now</button>
            </form>

        {% elif booked_listing and booked_listing.user == current_user %}
            <form method="post" action="{% url 'cancel_booking' booked_listing.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning">Cancel the booking</button>
            </form>

        {% elif not booked_listing %}
            <button disabled type="submit" class="btn">Already booked!</button>
        {% endif %}
    {% else %}
        {% if listing.is_active %}
            <form method="post" action="{% url 'toggle_listing' id=listing.id %}" style="display:inline;">
                {% csrf_token %}
                <button type="submit" name="action" value="deactivate" class="btn btn-danger">Deactivate</button>
            </form>
        {% elif not listing.is_active and not listing.booked %}
            <form method="post" action="{% url 'toggle_listing' id=listing.id %}" style="display:inline;">
                {% csrf_token %}
                <button type="submit" name="action" value="activate" class="btn btn-primary">Activate</button>
            </form>
        {% endif %}

        <form method="post" action="{% url 'delete_listing' id=listing.id %}" style="display:inline;">
            {% csrf_token %}
            <button type="submit" name="action" value="delete" class="btn btn-danger">Delete</button>
        </form>
    {% endif %}
</div>
{% endblock content %}

templates/my_listings.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<style>
    body {
        font-family: 'Arial', sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
    }

    ul {
        list-style: none;
        padding: 0;
    }

    li {
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 8px;
        margin: 10px 0;
        padding: 15px;
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    li a {
        text-decoration: none;
        color: #333;
        font-weight: bold;
        font-size: 1.2em;
    }

    .button-container {
        display: flex;
        gap: 10px; /* Adjust the gap as needed */
    }

    button {
        padding: 10px;
        cursor: pointer;
        border: none;
        border-radius: 4px;
        outline: none;
    }

    button.deactivate {
        background-color: #e74c3c;
        color: #fff;
    }

    button.activate {
        background-color: #3498db;
        color: #fff;
    }

    button.booked {
        background-color: #95a5a6;
        color: #fff;
    }

    button.delete {
        background-color: #e74c3c;
        color: #fff;
    }

    p.empty-message {
        text-align: center;
        margin-top: 30px;
    }
</style>

<ul>
    {% for listing in listings %}
        <li>
            <a href="{% url 'listing' id=listing.id %}">
                {{ listing }}
            </a>

            <div class="button-container">
                {% if listing.is_active %}
                    <form method="post" action="{% url 'toggle_listing' id=listing.id %}" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" name="action" value="deactivate" class="deactivate">Deactivate</button>
                    </form>
                {% elif not listing.is_active %}
                    {% if not listing.booked %}
                        <form method="post" action="{% url 'toggle_listing' id=listing.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" name="action" value="activate" class="activate">Activate</button>
                        </form>
                    {% else %}
                        <form method="post" action="{% url 'toggle_listing' id=listing.id %}" style="display:inline;">
                            {% csrf_token %}
                            <button type="submit" disabled name="action" value="activate" class="booked">Booked!</button>
                        </form>
                    {% endif %}
                {% endif %}

                <form method="post" action="{% url 'delete_listing' id=listing.id %}" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit" name="action" value="delete" class="delete">Delete</button>
                </form>
            </div>
        </li>
    {% empty %}
        <p class="empty-message">You have not posted any listings yet...</p>
    {% endfor %}
</ul>
{% endblock content %}

templates/new_listing.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<h2>Create a New Listing</h2>

<form method="POST" enctype="multipart/form-data">

    {% csrf_token %}

    {{ form.as_p }}<br>

    {{ formset.management_form }}
    {% for form in formset %}
        {{ form }}
    {% endfor %}
    <button type="submit">Submit</button>

</form>

{% endblock content %}

templates/profile.html
{% extends 'base.html' %}

{% block title %}User Profile{% endblock title %}

{% block content %}
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f8f9fa;
        }

        .profile-container {
            max-width: 600px;
            margin: 50px auto;
            padding: 20px;
            background-color: #ffffff;
            border: 1px solid #dee2e6;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        .user-info {
            margin-top: 20px;
        }

        h1 {
            text-align: center;
            color: #343a40;
        }
    </style>

<div class="profile-container">
    <h1>User Profile</h1>
    <div class="user-info">
        <p><strong>Username:</strong> {{ user.username }}</p>
        <p><strong>Email:</strong> {{ user.email }}</p>
        <p><strong>Balance:</strong> ${{ user.balance }}</p>
    </div>
    
    <!-- Add Edit button -->
    <a href="{% url 'edit_account' %}" class="btn btn-primary">Edit Account</a>
</div>
{% endblock content %}